spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dada?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mybatis/**.xml
